### ISSUE TITLE
Not possible to use feast_trino/connectors package

### ISSUE THREAD

**Issue by marcosvgj** [Shopify/feast-trino#41]
Following the current example in [README.md](https://github.com/Shopify/feast-trino#edit-feature_repoexamplepy), i got this issue: 
 ```python 
from feast_trino.connectors.upload import upload_pandas_dataframe_to_trino
```

## Expected Behavior

```python
>>> from feast_trino.connectors.upload import upload_pandas_dataframe_to_trino
>>> # Import successfully
```

## Current Behavior
```python
>>> from feast_trino.connectors.upload import upload_pandas_dataframe_to_trino
Feast is an open source project that collects anonymized error reporting and usage statistics. To opt out or learn more see https://docs.feast.dev/reference/usage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcosvgj/.cache/pypoetry/virtualenvs/fs-d0D1kt7D-py3.8/lib/python3.8/site-packages/feast_trino/__init__.py", line 3, in <module>
    from .trino import TrinoOfflineStore, TrinoOfflineStoreConfig
  File "/home/marcosvgj/.cache/pypoetry/virtualenvs/fs-d0D1kt7D-py3.8/lib/python3.8/site-packages/feast_trino/trino.py", line 19, in <module>
    from feast_trino.connectors.upload import upload_pandas_dataframe_to_trino
ModuleNotFoundError: No module named 'feast_trino.connectors'
```

## Steps to reproduce
Follow the current example in  [README.md](https://github.com/Shopify/feast-trino#edit-feature_repoexamplepy)

### Specifications

- Version: 1.0.0
- Platform: Linux
- Subsystem: Python 3.8.2

## Possible Solution

Include an empty `__init__.py` file into [`feast-trino/connectors/`](https://github.com/Shopify/feast-trino/tree/main/feast_trino/connectors) folder.

"_The __init__.py files are required to make Python treat directories containing the file as packages. This prevents directories with a common name, such as string, unintentionally hiding valid modules that occur later on the module search path. In the simplest case, __init__.py can just be an empty file, but it can also execute initialization code for the package or set the __all__ variable, described later._" -- https://docs.python.org/3/tutorial/modules.html

**Comment by MattDelac** [comment]
👋 

Thanks for trying feast-trino. Because of some issues currently going with pypi.org, this plugin is not officially published. Therefore to install it, you would have to run the following command in your terminal
```sh
pip install -e git+https://github.com/Shopify/feast-trino.git#egg=feast_trino
```

Once done, you can see that this works as expected.
![image](https://user-images.githubusercontent.com/18557047/146809761-ca627590-6230-447a-ac98-607c10b42c1d.png)

I will close this issue once `feast-trino` will officially be published in pypi.org. I will also update the README.md til it's solved

Let me know how it goes

**Comment by marcosvgj** [comment]
> 👋
> 
> Thanks for trying feast-trino. Because of some issues currently going with pypi.org, this plugin is not officially published. Therefore to install it, you would have to run the following command in your terminal
> 
> ```shell
> pip install -e git+https://github.com/Shopify/feast-trino.git#egg=feast_trino
> ```
> 
> Once done, you can see that this works as expected. ![image](https://user-images.githubusercontent.com/18557047/146809761-ca627590-6230-447a-ac98-607c10b42c1d.png)
> 
> I will close this issue once `feast-trino` will officially be published in pypi.org. I will also update the README.md til it's solved
> 
> Let me know how it goes

Thanks @MattDelac!
